# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  deployments: write
  contents: write
  statuses: write
  actions: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
    - name: Promote build to env
      run: |
          cd k8s/helm/dev/va6
          sed -i 's|tag:.*|tag: '${{ github.sha }}'|' values.yaml 
          git config --global user.name 'Sonam11'
          git config --global user.email 'Sonam11@github.com'
          git config --global user.password ${{ secrets.GIT_TOKEN }}
          git add values.yaml
          git commit -m "Update values.yaml git sha"
          git push
          
  manual-approval:
    environment: 'Prod'
    runs-on: ubuntu-20.04
    needs:
      - build-and-test
    steps:
      - run: echo "Approved to Prod"
      
  deploy-on-prod:
    name: 'Deploy to Prod'
    runs-on: ubuntu-latest
    needs: 
      - manual-approval
    steps:
      - name: Promote build to env
        run: |
          cd k8s/helm/dev/va6
          sed -i 's|tag:.*|tag: '${{ github.sha }}'|' values.yaml 
          git config --global user.name 'Sonam11'
          git config --global user.email 'Sonam11@github.com'
          git config --global user.password ${{ secrets.GIT_TOKEN }}
          git add values.yaml
          git commit -m "Update values.yaml git sha"
          git push
      
    
